# Generated by Django 5.2 on 2025-05-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "country",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Employ",
            fields=[
                ("licence_id", models.IntegerField(primary_key=True, serialize=False)),
                ("team_api_id", models.IntegerField(blank=True, null=True)),
                ("id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "employ",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                ("player_fifa_api_id", models.IntegerField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "follow",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FootballManager",
            fields=[
                ("licence_id", models.IntegerField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "football_manager",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Interested",
            fields=[
                ("licence_id", models.IntegerField(blank=True, null=True)),
                ("player_fifa_api_id", models.IntegerField(blank=True, null=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "interested",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("country_id", models.IntegerField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "league",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ManagerAccount",
            fields=[
                ("licence_id", models.IntegerField(blank=True, null=True)),
                ("username", models.TextField(blank=True, null=True)),
                ("password", models.TextField(blank=True, null=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "manager_account",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ManagerAccountUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("licence_id", models.IntegerField(blank=True, null=True)),
                ("username", models.TextField(unique=True)),
                ("password", models.TextField()),
            ],
            options={
                "db_table": "manager_account",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("season", models.TextField(blank=True, null=True)),
                ("stage", models.IntegerField(blank=True, null=True)),
                ("date", models.TextField(blank=True, null=True)),
                ("match_api_id", models.IntegerField(blank=True, null=True)),
                ("home_team_api_id", models.IntegerField(blank=True, null=True)),
                ("away_team_api_id", models.IntegerField(blank=True, null=True)),
                ("home_team_goal", models.IntegerField(blank=True, null=True)),
                ("away_team_goal", models.IntegerField(blank=True, null=True)),
                ("league_id", models.IntegerField(blank=True, null=True)),
                ("shoton1", models.IntegerField(blank=True, null=True)),
                ("shoton2", models.IntegerField(blank=True, null=True)),
                ("shotoff1", models.IntegerField(blank=True, null=True)),
                ("shotoff2", models.IntegerField(blank=True, null=True)),
                ("foulcommit1", models.IntegerField(blank=True, null=True)),
                ("foulcommit2", models.IntegerField(blank=True, null=True)),
                ("card1", models.IntegerField(blank=True, null=True)),
                ("card2", models.IntegerField(blank=True, null=True)),
                ("cross1", models.IntegerField(blank=True, null=True)),
                ("cross2", models.IntegerField(blank=True, null=True)),
                ("corner1", models.IntegerField(blank=True, null=True)),
                ("corner2", models.IntegerField(blank=True, null=True)),
                ("possession1", models.IntegerField(blank=True, null=True)),
                ("possession2", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "match",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.IntegerField(blank=True, null=True)),
                ("player_api_id", models.IntegerField(blank=True, null=True)),
                ("player_name", models.TextField(blank=True, null=True)),
                (
                    "player_fifa_api_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("birthday", models.TextField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("league_id", models.IntegerField(blank=True, null=True)),
                ("team_api_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "player",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerAttributes",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("player_fifa_api_id", models.IntegerField(blank=True, null=True)),
                ("player_api_id", models.IntegerField(blank=True, null=True)),
                ("date", models.TextField(blank=True, null=True)),
                ("overall_rating", models.TextField(blank=True, null=True)),
                ("potential", models.TextField(blank=True, null=True)),
                ("preferred_foot", models.TextField(blank=True, null=True)),
                ("attacking_work_rate", models.TextField(blank=True, null=True)),
                ("defensive_work_rate", models.TextField(blank=True, null=True)),
                ("crossing", models.TextField(blank=True, null=True)),
                ("finishing", models.TextField(blank=True, null=True)),
                ("heading_accuracy", models.TextField(blank=True, null=True)),
                ("short_passing", models.TextField(blank=True, null=True)),
                ("volleys", models.TextField(blank=True, null=True)),
                ("dribbling", models.TextField(blank=True, null=True)),
                ("curve", models.TextField(blank=True, null=True)),
                ("free_kick_accuracy", models.TextField(blank=True, null=True)),
                ("long_passing", models.TextField(blank=True, null=True)),
                ("ball_control", models.TextField(blank=True, null=True)),
                ("acceleration", models.TextField(blank=True, null=True)),
                ("sprint_speed", models.TextField(blank=True, null=True)),
                ("agility", models.TextField(blank=True, null=True)),
                ("reactions", models.TextField(blank=True, null=True)),
                ("balance", models.TextField(blank=True, null=True)),
                ("shot_power", models.TextField(blank=True, null=True)),
                ("jumping", models.TextField(blank=True, null=True)),
                ("stamina", models.TextField(blank=True, null=True)),
                ("strength", models.TextField(blank=True, null=True)),
                ("long_shots", models.TextField(blank=True, null=True)),
                ("aggression", models.TextField(blank=True, null=True)),
                ("interceptions", models.TextField(blank=True, null=True)),
                ("positioning", models.TextField(blank=True, null=True)),
                ("vision", models.TextField(blank=True, null=True)),
                ("penalties", models.TextField(blank=True, null=True)),
                ("marking", models.TextField(blank=True, null=True)),
                ("standing_tackle", models.TextField(blank=True, null=True)),
                ("sliding_tackle", models.TextField(blank=True, null=True)),
                ("gk_diving", models.TextField(blank=True, null=True)),
                ("gk_handling", models.TextField(blank=True, null=True)),
                ("gk_kicking", models.TextField(blank=True, null=True)),
                ("gk_positioning", models.TextField(blank=True, null=True)),
                ("gk_reflexes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "player_attributes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                ("team_api_id", models.IntegerField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "subscribe",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.IntegerField(blank=True, null=True)),
                ("team_api_id", models.IntegerField(primary_key=True, serialize=False)),
                ("team_long_name", models.TextField(blank=True, null=True)),
                ("team_short_name", models.TextField(blank=True, null=True)),
                ("league_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "team",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TeamAttributes",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("team_fifa_api_id", models.IntegerField(blank=True, null=True)),
                ("team_api_id", models.IntegerField(blank=True, null=True)),
                ("date", models.TextField(blank=True, null=True)),
                (
                    "buildupplayspeed",
                    models.IntegerField(
                        blank=True, db_column="buildUpPlaySpeed", null=True
                    ),
                ),
                (
                    "buildupplayspeedclass",
                    models.TextField(
                        blank=True, db_column="buildUpPlaySpeedClass", null=True
                    ),
                ),
                (
                    "buildupplaydribbling",
                    models.IntegerField(
                        blank=True, db_column="buildUpPlayDribbling", null=True
                    ),
                ),
                (
                    "buildupplaydribblingclass",
                    models.TextField(
                        blank=True, db_column="buildUpPlayDribblingClass", null=True
                    ),
                ),
                (
                    "buildupplaypassing",
                    models.IntegerField(
                        blank=True, db_column="buildUpPlayPassing", null=True
                    ),
                ),
                (
                    "buildupplaypassingclass",
                    models.TextField(
                        blank=True, db_column="buildUpPlayPassingClass", null=True
                    ),
                ),
                (
                    "buildupplaypositioningclass",
                    models.TextField(
                        blank=True, db_column="buildUpPlayPositioningClass", null=True
                    ),
                ),
                (
                    "chancecreationpassing",
                    models.IntegerField(
                        blank=True, db_column="chanceCreationPassing", null=True
                    ),
                ),
                (
                    "chancecreationpassingclass",
                    models.TextField(
                        blank=True, db_column="chanceCreationPassingClass", null=True
                    ),
                ),
                (
                    "chancecreationcrossing",
                    models.IntegerField(
                        blank=True, db_column="chanceCreationCrossing", null=True
                    ),
                ),
                (
                    "chancecreationcrossingclass",
                    models.TextField(
                        blank=True, db_column="chanceCreationCrossingClass", null=True
                    ),
                ),
                (
                    "chancecreationshooting",
                    models.IntegerField(
                        blank=True, db_column="chanceCreationShooting", null=True
                    ),
                ),
                (
                    "chancecreationshootingclass",
                    models.TextField(
                        blank=True, db_column="chanceCreationShootingClass", null=True
                    ),
                ),
                (
                    "chancecreationpositioningclass",
                    models.TextField(
                        blank=True,
                        db_column="chanceCreationPositioningClass",
                        null=True,
                    ),
                ),
                (
                    "defencepressure",
                    models.IntegerField(
                        blank=True, db_column="defencePressure", null=True
                    ),
                ),
                (
                    "defencepressureclass",
                    models.TextField(
                        blank=True, db_column="defencePressureClass", null=True
                    ),
                ),
                (
                    "defenceaggression",
                    models.IntegerField(
                        blank=True, db_column="defenceAggression", null=True
                    ),
                ),
                (
                    "defenceaggressionclass",
                    models.TextField(
                        blank=True, db_column="defenceAggressionClass", null=True
                    ),
                ),
                (
                    "defenceteamwidth",
                    models.IntegerField(
                        blank=True, db_column="defenceTeamWidth", null=True
                    ),
                ),
                (
                    "defenceteamwidthclass",
                    models.TextField(
                        blank=True, db_column="defenceTeamWidthClass", null=True
                    ),
                ),
                (
                    "defencedefenderlineclass",
                    models.TextField(
                        blank=True, db_column="defenceDefenderLineClass", null=True
                    ),
                ),
            ],
            options={
                "db_table": "team_attributes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField()),
                ("name", models.TextField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("username", models.TextField(blank=True, null=True)),
                ("password", models.TextField(blank=True, null=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "user_account",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserAccountUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("username", models.TextField(unique=True)),
                ("password", models.TextField()),
            ],
            options={
                "db_table": "user_account",
                "managed": False,
            },
        ),
    ]
